### ISSUE TITLE
sortByRank function failing in python 3.7

### ISSUE THREAD

**Issue by hdavit** [sllloyd/vaccine_predictions#1]
Hello - thanks for the great paper and for making the code available.

It adjusted a few lines to be compatible with python 3.7+, but I am stuck on this one given I don not get the logic:

```
		def sortByRank(a, b):
			for phase in range(len(params['phases'])):
				i = len(params['phases']) - phase - 1
				comp = cmp(b['finished'][i]['aveEff'], a['finished'][i]['aveEff'])
				if comp != 0: 
					return comp
				comp = cmp(a['finished'][i]['aveMon'], b['finished'][i]['aveMon'])
				if comp != 0: 
					return comp
			return comp
```

the `cmp` variable is noit referened (typo ?), and the call: `vaccines.sort(key=sortByRank)` fails due to

```
TypeError: sortByRank() missing 1 required positional argument: 'b'
```

Any help ? Thanks a lot !

**Comment by sllloyd** [comment]
Hi,
  This function sorts vaccines based on their average success at each phase (backwards). If they are the same it compares the average times instead. cmp is a function that seems to have gone away in Python 3. Someone suggests replacing it with this:

def cmp(a, b):
	return (a > b) - (a < b)
  
I haven't tested this.
  Cheers
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Steve Lloyd                      
Emeritus Professor, School of Physics and Astronomy
Queen Mary University of London, Mile End Road, London E1 4NS, UK
E-mail: s.l.lloyd@qmul.ac.uk
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by hdavit** [comment]
Thanks a lot !

I used a combination of what you indicated and some elements found [here](https://stackoverflow.com/questions/5213033/sort-a-list-of-lists-with-a-custom-compare-function), which **seems to work** (haven't parsed through the output yet)

```
		# Sort vaccines by success
		import functools

		def sortByRank(a, b):
			# sorts vaccines based on their average success at each phase (backwards). If they are the same it compares the average times instead
			def cmp(a, b):
				# If a>b returns 1, if a<b returns -1, if equal returns 0
				return (a > b) - (a < b)

			for phase in range(len(params['phases'])):
				i = len(params['phases']) - phase - 1
				comp = cmp(b['finished'][i]['aveEff'], a['finished'][i]['aveEff'])
				if comp != 0:
					return comp
				comp = cmp(a['finished'][i]['aveMon'], b['finished'][i]['aveMon'])
				if comp != 0:
					return comp
			return comp
			
		vaccines = sorted(vaccines, key=functools.cmp_to_key(sortByRank))
```
